CREATE TABLE IF NOT EXISTS transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL,
    type ENUM('INCOME', 'EXPENSE') NOT NULL,
    category ENUM('FOOD', 'TRANSPORT', 'UTILITIES', 'ENTERTAINMENT', 'SHOPPING', 'RENT','SALARY', 'OTHER') NOT NULL,
    description VARCHAR(255) NOT NULL,
    date DATE  DEFAULT CURRENT_DATE
);
